export const Users = [
  {
    id: 1,
    profilePicture: "assets/profiles/1.jpg",
    username: "John Doe",
  },
  {
    id: 2,
    profilePicture: "assets/profiles/2.jpg",
    username: "Ponnappa Priya",
  },
  {
    id: 3,
    profilePicture: "assets/profiles/3.jpg",
    username: "Ang Li",
  },
  {
    id: 4,
    profilePicture: "assets/profiles/4.jpg",
    username: "Trevor Virtue",
  },
  {
    id: 5,
    profilePicture: "assets/profiles/5.jpg",
    username: "Verona Blair",
  },
  {
    id: 6,
    profilePicture: "assets/profiles/6.jpg",
    username: "Jane Meldrum",
  },
  {
    id: 7,
    profilePicture: "assets/profiles/7.jpg",
    username: "Desiree Burch",
  },
  {
    id: 8,
    profilePicture: "assets/profiles/8.jpg",
    username: "Andrew Kazantzis",
  },
  {
    id: 9,
    profilePicture: "assets/profiles/9.jpg",
    username: "Daly Harry",
  },
  {
    id: 10,
    profilePicture: "assets/profiles/10.jpg",
    username: "Ruveni Ellawala",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "I never knew what hardship looked like until it started raining bowling balls.",
    photo: "assets/post/1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "Mary realized if her calculator had a history, it would be more embarrassing than her computer browser history.",
    photo: "assets/post/2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 20,
    comment: 19,
  },
  {
    id: 3,
    desc: "The golden retriever loved the fireworks each Fourth of July.",
    photo: "assets/post/3.jpg",
    date: "55 mins ago",
    userId: 3,
    like: 54,
    comment: 29,
  },
  {
    id: 4,
    desc: "I liked their first two albums but changed my mind after that charity gig.",
    photo: "assets/post/4.jpg",
    date: "5 hours ago",
    userId: 4,
    like: 41,
    comment: 15,
  },
  {
    id: 5,
    desc: "When money was tight, he'd get his lunch money from the local wishing well.",
    photo: "assets/post/5.jpg",
    date: "9 hours ago",
    userId: 5,
    like: 320,
    comment: 90,
  },
  {
    id: 6,
    desc: "The light that burns twice as bright burns half as long.",
    photo: "assets/post/6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 302,
    comment: 85,
  },
  {
    id: 7,
    desc: "Don't put peanut butter on the dog's nose.",
    photo: "assets/post/7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 12,
    comment: 5,
  },
  {
    id: 8,
    desc: "He had accidentally hacked into his company's server.",
    photo: "assets/post/8.jpg",
    date: "3 days ago",
    userId: 8,
    like: 192,
    comment: 59,
  },
  {
    id: 9,
    desc: "He realized there had been several deaths on this road, but his concern rose when he saw the exact number.",
    photo: "assets/post/9.jpg",
    date: "4 days ago",
    userId: 9,
    like: 116,
    comment: 24,
  },
  {
    id: 10,
    desc: "Nobody questions who built the pyramids in Mexico.",
    photo: "assets/post/10.jpg",
    date: "1 week ago",
    userId: 10,
    like: 512,
    comment: 69,
  },
];
